name: Solar Tests

on:
  workflow_dispatch:
    inputs:
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"

jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      # https://playwright.dev/python/docs/docker
      image: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_LOGIN: ${{ secrets.ADMIN_LOGIN }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      TEST_USERS: ${{ secrets.TEST_USERS }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip -r requirements.txt
        playwright install --with-deps chromium
    - name: Run the tests
      run: pytest
